# serverless.yml

service: users

custom:
  tableName: 'users-table-${self:provider.stage}'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  documentation:
    version: 'v1'
    title: 'Users App'
    description: 'This is Users App'
    models: {}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getUser:
    handler: src/controllers/users/get-user/index.handler
    events:
      - http: 'GET api/v1/user/{proxy+}'
  createUser:
    handler: src/controllers/users/create-user/index.handler
    events:
      - http: 'POST api/v1/user'
  deleteUser:
    handler: src/controllers/users/delete-user/index.handler
    events:
      - http: 'DELETE api/v1/user/{proxy+}'
  updateUser:
    handler: src/controllers/users/update-user/index.handler
    events:
      - http: 'PUT api/v1/user'
  listUsers:
    handler: src/controllers/users/list-users/index.handler
    events:
      - http: 'GET api/v1/user/{proxy+}'

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline